aggregateDataSets <- function(all.data,
                              in.sub,
                              in.meta,
                              in.errors){
  all.data <- list(sub  = rbind(all.data$sub,
                                in.sub),
                   meta =  rbind(all.data$meta,
                                 in.meta),
                   errors = list(by.WS = rbind(all.data$errors$by.WS,
                                               data.frame(data.file = in.sub$data.file,
                                                          in.errors$by.WS)),
                                 by.TOD = rbind(all.data$errors$by.TOD,
                                                data.frame(data.file = in.sub$data.file,
                                                           in.errors$by.TOD)),
                                 by.CM = rbind(all.data$errors$by.CM,
                                               data.frame(data.file = in.sub$data.file,
                                                          in.errors$by.CM)),
                                 by.WD = rbind(all.data$errors$by.WD,
                                               data.frame(data.file = in.sub$data.file,
                                                          in.errors$by.WD)),
                                 by.Range = rbind(all.data$errors$by.Range,
                                                  data.frame(data.file = in.sub$data.file,
                                                             in.errors$by.Range)),
                                 by.4CM = rbind(all.data$errors$by.4CM,
                                                data.frame(data.file = in.sub$data.file,
                                                           in.errors$by.4CM))))
}